version: "3.9"

services:
  wisdom-server:
    build:
      dockerfile: ./docker/server/Dockerfile
      context: ..
    tty: true
    ports:
    - "7777:7777"

  wisdom-client:
    build:
      dockerfile: ./docker/client/Dockerfile
      context: ..
    tty: true
